version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/wwww"
      - "/wwww/openspace"
    schedule:
      interval: "weekly"
    groups:
      appdynamics:
        patterns:
          - "appdynamics/*"
